version: '3'
services:
  db:
    image: mysql:9.6
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: 'realrank'
      MYSQL_USER: 'hong8159'
      MYSQL_PASSWORD: '3342'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - './mysql-data:/var/lib/mysql'
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - './redis_data:/data'
    restart: always


